<x-layouts.account title="Retenir une proposition" space="client">
  <nav class="crumbs" aria-label="Fil d’Ariane"><a class="back-m" href="{{ route('client.missions.proposals', $mission->getKey()) }}"><x-fc.icon name="arrow-right" :size="16" class="flip" />Propositions</a><a class="hide-m" href="{{ route('client.missions') }}">Mes missions</a><span class="sep hide-m" aria-hidden="true">›</span><span class="hide-m" aria-current="page">Retenir une proposition</span></nav>
  <section class="card" style="max-width:720px" aria-labelledby="c-title"><h1 class="t-h1" id="c-title">Retenir la proposition de {{ $item['author'] }}</h1><p class="muted" style="margin-top:6px">{{ $live->title }} · version {{ $item['number'] }} de la proposition</p>
    <h2 class="t-h2 card-title" style="margin-top:16px">Conditions que vous acceptez</h2>
    <dl class="defs"><div><dt>Prix ferme</dt><dd><x-fc.money :amount="$item['price']" /></dd></div><div><dt>Délai</dt><dd>{{ $item['days'] }} jours à partir du départ du travail</dd></div><div><dt>Corrections incluses</dt><dd>{{ $item['revisions'] }}</dd></div>
      <div><dt>Périmètre</dt><dd>{{ $item['scope'] }}</dd></div><div><dt>Livrables</dt><dd>@foreach($item['deliverables'] as $d){{ $d }}@if(! $loop->last)<br>@endif @endforeach</dd></div><div><dt>Mode de livraison</dt><dd>{{ $item['mode'] }}</dd></div><div><dt>Valable jusqu’au</dt><dd>{{ $item['validUntil'] }}</dd></div></dl>
    <div class="notice tone-info" style="margin-top:12px"><x-fc.icon name="info" /><div><p><strong>Ce qui va se passer</strong></p><ul class="stack-sm" style="padding-left:18px;list-style:disc;margin-top:6px">
      <li>La mission est <strong>réservée</strong> et une <strong>commande</strong> est créée avec ces conditions <strong>figées</strong> : elles ne seront jamais recalculées.</li>
      <li>La commande attend le <strong>paiement</strong>. La mission n’est <strong>attribuée</strong> qu’une fois le paiement confirmé côté serveur ; <strong>aucun travail ne commence</strong> sans paiement confirmé et brief complet.</li>
      <li>Si vous annulez la commande ou si elle expire avant paiement, la proposition est libérée et la mission passe en « sélection terminée » : <strong>rien n’est rouvert automatiquement</strong>, vous choisissez de la rouvrir ou de la fermer.</li>
      <li>Vous ne pouvez retenir qu’<strong>une seule</strong> proposition à la fois.</li></ul></div></div>
    @if($errors->any())<div class="notice tone-error" role="alert"><x-fc.icon name="error" /><p>Vérifiez les champs signalés ci-dessous. Vos saisies sont conservées.</p></div>@endif
    <form method="post" action="{{ route('client.missions.select.store', [$mission->getKey(), $item['versionId']]) }}" data-once style="display:grid;gap:16px;margin-top:16px" novalidate>@csrf
      <input type="hidden" name="expected_version" value="{{ $mission->row_version }}"><input type="hidden" name="operation_key" value="{{ $operationKey }}">
      @if(count($live->client_inputs))<h2 class="t-h2 card-title">Votre brief (privé)</h2><p class="muted small">Vos réponses ne sont communiquées qu’au freelance retenu, dans la commande.</p>
        @foreach($live->client_inputs as $k => $label)@php($e = $errors->first('answers.'.$k))<div class="field"><label for="a-{{ $k }}">{{ $label }}</label><textarea class="textarea" id="a-{{ $k }}" name="answers[{{ $k }}]" rows="2" maxlength="1000" required @if($e) aria-invalid="true" aria-describedby="ae-{{ $k }}" @endif>{{ old('answers.'.$k) }}</textarea>@if($e)<p class="field-error" id="ae-{{ $k }}"><x-fc.icon name="error" :size="16" />{{ $e }}</p>@endif</div>@endforeach @endif
      <div class="field"><label for="notes">Précisions (facultatif)</label><textarea class="textarea" id="notes" name="notes" rows="3" maxlength="3000">{{ old('notes') }}</textarea></div>
      <div class="field"><label class="check" for="conditions"><input type="checkbox" id="conditions" name="conditions" value="1" required @checked(old('conditions'))> <span>J’ai lu les conditions de cette proposition (prix, délai, corrections, périmètre, livrables) et je les accepte.</span></label>@error('conditions')<p class="field-error"><x-fc.icon name="error" :size="16" />{{ $message }}</p>@enderror</div>
      <div class="row"><button class="btn btn-primary btn-lg" type="submit" data-once-label="Enregistrement…">Retenir cette proposition</button><a class="btn btn-link" href="{{ route('client.missions.proposals', $mission->getKey()) }}">Revenir aux propositions</a></div>
    </form></section>
</x-layouts.account>
